### ISSUE TITLE
MFA with certificate

### ISSUE THREAD

**Issue by alexandre-grigoriev** [rzdebskiy/MFATestADAL#2]
First of all, thank you for your realization. It works perfectly in my XAMARIN application which connects to Dynamics 365 CRM. 
The problem is that MFA with user certificate delivered by AD and installed on smartphone or on UWP device cannot be send back to AD to verify a user. 
This type of MFA is supported by browsers like Chrome or Edge. First, you see standard authentication popup. When you enter a login, the authentication sends you to a custom authorization page. You enter your password and the custom authorization page shows a message that a certificate required, and browser shows popup with a list of certificates installed on a local computer. You select and, in some seconds, you are connected to CRM.
My XAMARIN application stop working, and I cannot find how to pass a certificate or to realize this handshaking procedure. Do you have some ideas about this issue?  
Alexandre

**Comment by rzdebskiy** [comment]
@alexandre-grigoriev thank you for kind words, I didn't quite get the issue. Could you give more details?  You have mentioned "It works perfectly in my XAMARIN application" - did I get it right that my sample works for you, but you made some modifications and now it doesn't? If yes - could you please give more details of all modifications and what actually you are trying to achieve?
